### ISSUE TITLE
Incorrect db column size

### ISSUE THREAD

**Issue by yuanzhou** [bd2kccd/ccd-annotations#4]
@marksilvis I noticed an error when testing the updated annotation against changes that @kvb2univpitt made in causal web.

I couldn't add text with more than 255 characters. 

![capture](https://cloud.githubusercontent.com/assets/195873/20943953/9b7f3e60-bbcf-11e6-8c20-19ab8850b931.PNG)

According to @kvb2univpitt, in the ccd-db v0.6.3 branch, it needs to specify the size of the string field as text, otherwise it uses varchar(255) in MySQL. 

https://github.com/bd2kccd/ccd-db/blob/v0.6.3/src/main/java/edu/pitt/dbmi/ccd/db/entity/AnnotationData.java#L58

**Comment by marksilvis** [comment]
I set the database column size to 1000 characters for now. I am adding an error message to the Annotations API when a user tries to create an annotation with more than 1000 characters.

Additionally, I will update the text field in ccd-web to show the user how much of the maximum size they've used.

**Comment by marksilvis** [comment]
This issue is fixed. A new issue was created regarding the error message response.
